# vou usar essa imagem como base
 FROM chuanwen/cowsay:latest
# Lembre-se que com ele, diferente do CMD o comando não poderá ser sobrescrito com o docker run, porém, conseguiremos passar parâmetros ao binário, exploraremos esse recurso para poder passar a mensagem.
# indica qual comando deve ser executado ao iniciar o container
ENTRYPOINT [ "/usr/games/cowsay" ]
# indica qual comando deve ser executado toda vez q  iniciar o container  cdm pode ser sobreescrito se tiver mais de um somnte o ultimo executa
CMD [ "#VQV Trybe" ]
